import SignIn from "components/SignIn";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import AuthController from "../controllers/AuthController";
import styles from "../styles/Home.module.scss";

export default function Home() {
  const [signUp, setSignUp] = useState<boolean>(false);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Note Ladder</h1>

        <div>
          <SignIn onSignUp={() => setSignUp(true)} />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
